# Generated by Django 3.1.3 on 2020-11-02 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=160)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('visibility', models.IntegerField()),
                ('wind', models.CharField(max_length=160)),
                ('last_update', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
